apiVersion: v1
kind: Secret
metadata:
  name: repo-hol-gitops-apps
  namespace: REPLACE-WITH-ELW-NAMESPACE
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.vcf.lab/hol-gitops/apps.git
  username: argocd
  password: REPLACE-WITH-ARGOCD-DEPLOY-TOKEN
