apiVersion: v1
kind: Secret
metadata:
  name: repo-hol-gitops-apps
  namespace: ns-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.vcf.lab/hol-scitech-gitops/apps.git
  username: oauth2
  password: REPLACE-WITH-GITOPS-READ-PAT
